In [1]:
'''Modelo preditivo de classificaçãp para prever o valor de uma variável binária (true ou false) 
a partir de dados numéricos'''

In [2]:
# Import dos módulos
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
#import warnings
#warnings.filterwarnings("ignore")

In [3]:
# Dados de treino
n_train = 10
np.random.seed(0)
df_treino = pd.DataFrame({"var1": np.random.random(n_train), \
                          "var2": np.random.random(n_train), \
                          "var3": np.random.random(n_train), \
                          "var4": np.random.randint(0,2,n_train).astype(bool),\
                          "target": np.random.randint(0,2,n_train).astype(bool)})

In [5]:
# Dados de teste
n_test = 3
np.random.seed(1)
df_teste = pd.DataFrame({"var1": np.random.random(n_test), \
                         "var2": np.random.random(n_test), \
                         "var3": np.random.random(n_test), \
                         "var4": np.random.randint(0,2,n_test).astype(bool),\
                         "target": np.random.randint(0,2,n_test).astype(bool)})

In [6]:
# Crie um modelo com PCA para redução de dimensionalidade com 3 componentes
# Aplique o PCA aos datasets

In [7]:
df_treino

var1      var2      var3   var4  target
0  0.548814  0.791725  0.978618   True    True
1  0.715189  0.528895  0.799159  False    True
2  0.602763  0.568045  0.461479   True   False
3  0.544883  0.925597  0.780529  False   False
4  0.423655  0.071036  0.118274   True   False
5  0.645894  0.087129  0.639921  False    True
6  0.437587  0.020218  0.143353  False    True
7  0.891773  0.832620  0.944669  False   False
8  0.963663  0.778157  0.521848  False    True
9  0.383442  0.870012  0.414662  False   False

In [10]:
array = df_treino.values
# Separando o array em componentes de input e output
X = array[:,0:-1]
Y = array[:,-1]

In [15]:
from sklearn.preprocessing import MinMaxScaler
# Normalizando os dados
scaler = MinMaxScaler(feature_range = (0, 1))
rescaledX = scaler.fit_transform(X)

In [17]:
rescaledX

array([[0.28501539, 0.85213738, 1.        , 1.        ],
       [0.57176095, 0.56183869, 0.79140926, 0.        ],
       [0.37799695, 0.60507989, 0.39891598, 1.        ],
       [0.27824156, 1.        , 0.76975584, 0.        ],
       [0.06930681, 0.05612865, 0.        , 1.        ],
       [0.45233193, 0.07390381, 0.60632334, 0.        ],
       [0.09331905, 0.        , 0.02914981, 0.        ],
       [0.8760994 , 0.89730613, 0.9605397 , 0.        ],
       [1.        , 0.83715106, 0.46908438, 0.        ],
       [0.        , 0.93860633, 0.34449888, 0.        ]])

In [18]:
# Seleção de atributos
pca = PCA(n_components = 3)
fit = pca.fit(rescaledX)

In [38]:
pca

PCA(copy=True, iterated_power='auto', n_components=3, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [22]:
# Sumarizando os componentes
print("Variância: %s" % fit.explained_variance_ratio_)

Variância: [0.49061404 0.31668308 0.12626501]


In [23]:
print(fit.components_)

[[-0.41560616 -0.49822569 -0.45781234  0.60782443]
 [ 0.07720077  0.48986738  0.41182185  0.76450818]
 [-0.79428491  0.55578255 -0.14582199 -0.19736564]]


In [26]:
# Crie dataframes do pandas com o resultado do item anterior
pd.DataFrame(fit.components_)

0         1         2         3
0 -0.415606 -0.498226 -0.457812  0.607824
1  0.077201  0.489867  0.411822  0.764508
2 -0.794285  0.555783 -0.145822 -0.197366

In [31]:
# Crie um modelo de regressão logística
from sklearn.linear_model import LogisticRegression

# Datasets de treino e de teste
array_treino = df_treino.values
x_treino = array_treino[:,0:-1]
y_treino = array_treino[:,-1]
array_teste = df_teste.values
x_teste = array_teste[:,0:-1]

In [36]:
y_treino

array([True, True, False, False, False, True, True, False, True, False],
      dtype=object)

In [37]:
# Criando o objeto logistic regression 
modelo = LogisticRegression()
# Treinando o modelo com dados de treino e checando o score
modelo.fit(x_treino, y_treino)

C:\Users\cassi\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


ValueError: Unknown label type: 'unknown'

In [32]:
modelo.score(x_treino, y_treino)# Coletando os coeficientes
print('Coefficient: \n', modelo.coef_)

C:\Users\cassi\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


ValueError: Unknown label type: 'unknown'

In [ ]:
print('Intercept: \n', modelo.intercept_)

In [ ]:
# Previsões
valores_previstos = modelo.predict(x_teste)